/// This file is the entry point for the `rust-wa-protocol-proto` crate.
///
/// It uses the `include!` macro to bring the Rust code generated by `prost-build`
/// into this crate's scope, making it available to other crates that depend on this one.

// The name "waproto" here is derived from the `package waproto;` line in your .proto file.
// `prost` will generate a file named `waproto.rs` in the output directory.
// If you change the package name, you must change it here as well.
pub mod waproto {
    include!(concat!(env!("OUT_DIR"), "/waproto.rs"));
}
